runtime: python38

env_variables:
  FN_AUTH_REDIRECT_URI: http://www.glowscriptdev.spvi.net/google/auth
  FN_BASE_URI: http://www.glowscriptdev.spvi.net

handlers:
- url: /css
  static_dir: css

- url: /
  script: auto

- url: /ide.js
  static_files: ide/ide.js
  upload: ide/ide.js

- url: /lib
  static_dir: lib

- url: /package
  static_dir: package

- url: /docs
  static_dir: docs

- url: /api/.*
  script: auto
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /untrusted
  static_dir: untrusted
