version: "2"
services:
  datastore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    ports:
    - 8081:8081
    volumes:
     - datastore:/root
    command: gcloud beta emulators datastore start --host-port=0.0.0.0:8081 --project glowscript-dev

volumes:
  datastore:
